/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData bookmark_plus_outline = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData map_marker_plus_outline = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData map_marker_outline = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData map_outline = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData bookmark_multiple_outline = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData calendar_outline = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData bookmark_outline = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData flask_outline = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cloud_upload_outline = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cog_outline = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData crosshairs_off = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData hospital_box_outline = IconData(0xe80b, fontFamily: _kFontFam);
}
